package com.hpre.app.core.designsystem

import androidx.compose.ui.graphics.Color

// Brand mark — identity accent only, not a background for small text.
val HPreRed = Color(0xFFE53935)

// Brand gradient stops: coral → red → rose. Matches the launcher icon's warm ramp.
val HPreBrandCoral = Color(0xFFFF6F60)
val HPreBrandRose = Color(0xFFD6246E)

// LIVE badge — dedicated status token, kept separate from semantic error roles.
val HPreLiveBadge = Color(0xFFD01F3C)
val HPreOnLiveBadge = Color(0xFFFFFFFF)

// Dark theme — "midnight": neutral-cool surfaces with a faint indigo undertone.
val HPreDarkBackground = Color(0xFF0D0E17)
val HPreDarkSurfaceContainerLowest = Color(0xFF090A11)
val HPreDarkSurfaceContainerLow = Color(0xFF14151F)
val HPreDarkSurfaceContainer = Color(0xFF1A1C28)
val HPreDarkSurfaceContainerHigh = Color(0xFF222433)
val HPreDarkSurfaceContainerHighest = Color(0xFF2A2D3E)
val HPreDarkSurfaceVariant = Color(0xFF262939)
val HPreDarkOnSurface = Color(0xFFF3F3F8)
val HPreDarkOnSurfaceVariant = Color(0xFFAEB1C6)
val HPreDarkPrimary = Color(0xFFFF8A80)
val HPreDarkOnPrimary = Color(0xFF3F0008)
val HPreDarkPrimaryContainer = Color(0xFF5E1726)
val HPreDarkOnPrimaryContainer = Color(0xFFFFDADE)
val HPreDarkSecondary = Color(0xFFBDB6FF)
val HPreDarkOnSecondary = Color(0xFF221A5C)
val HPreDarkSecondaryContainer = Color(0xFF2F2A55)
val HPreDarkOnSecondaryContainer = Color(0xFFE5E1FF)
val HPreDarkTertiary = Color(0xFFFFC46B)
val HPreDarkOnTertiary = Color(0xFF402C00)
val HPreDarkTertiaryContainer = Color(0xFF4D3700)
val HPreDarkOnTertiaryContainer = Color(0xFFFFDFA8)
val HPreDarkOutline = Color(0xFF878AA0)
val HPreDarkOutlineVariant = Color(0xFF363A4D)
val HPreDarkError = Color(0xFFF2B8B5)
val HPreDarkOnError = Color(0xFF601410)
val HPreDarkErrorContainer = Color(0xFF8C1D18)
val HPreDarkOnErrorContainer = Color(0xFFF9DEDC)
val HPreDarkInverseSurface = Color(0xFFE4E4EC)
val HPreDarkInverseOnSurface = Color(0xFF262833)
val HPreDarkSurfaceDim = Color(0xFF08090F)
val HPreDarkSurfaceBright = Color(0xFF34374A)

// Light theme — warm paper whites with a faint lilac undertone.
val HPreLightBackground = Color(0xFFFAF8FB)
val HPreLightSurface = Color(0xFFFFFFFF)
val HPreLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val HPreLightSurfaceContainerLow = Color(0xFFF6F3F8)
val HPreLightSurfaceContainer = Color(0xFFF0ECF3)
val HPreLightSurfaceContainerHigh = Color(0xFFEAE5EE)
val HPreLightSurfaceContainerHighest = Color(0xFFE3DEE9)
val HPreLightSurfaceVariant = Color(0xFFE8E3EC)
val HPreLightOnSurface = Color(0xFF1B1A22)
val HPreLightOnSurfaceVariant = Color(0xFF585566)
val HPreLightPrimary = Color(0xFFC62838)
val HPreLightOnPrimary = Color(0xFFFFFFFF)
val HPreLightPrimaryContainer = Color(0xFFFFE0E2)
val HPreLightOnPrimaryContainer = Color(0xFF40000C)
val HPreLightSecondary = Color(0xFF5A4FC2)
val HPreLightOnSecondary = Color(0xFFFFFFFF)
val HPreLightSecondaryContainer = Color(0xFFE6E2FF)
val HPreLightOnSecondaryContainer = Color(0xFF1A1152)
val HPreLightTertiary = Color(0xFF855000)
val HPreLightOnTertiary = Color(0xFFFFFFFF)
val HPreLightTertiaryContainer = Color(0xFFFFDDB3)
val HPreLightOnTertiaryContainer = Color(0xFF2B1700)
val HPreLightOutline = Color(0xFF787485)
val HPreLightOutlineVariant = Color(0xFFD6D1DC)
val HPreLightError = Color(0xFFB3261D)
val HPreLightOnError = Color(0xFFFFFFFF)
val HPreLightErrorContainer = Color(0xFFF9DEDC)
val HPreLightOnErrorContainer = Color(0xFF410002)
val HPreLightInverseSurface = Color(0xFF2F2E37)
val HPreLightInverseOnSurface = Color(0xFFF5F2F8)
val HPreLightSurfaceDim = Color(0xFFDCD7E0)
val HPreLightSurfaceBright = Color(0xFFFFFFFF)
