package com.hpre.app.core.designsystem

import androidx.compose.ui.graphics.Color

// Brand mark — identity accent only, not a background for small text.
val HPreRed = Color(0xFFE53935)

// LIVE badge — dedicated status token, kept separate from semantic error roles.
val HPreLiveBadge = Color(0xFFB32624)
val HPreOnLiveBadge = Color(0xFFFFFFFF)

// Dark theme — spec section 2.3
val HPreDarkBackground = Color(0xFF101114)
val HPreDarkSurfaceContainerLowest = Color(0xFF0C0D10)
val HPreDarkSurfaceContainerLow = Color(0xFF17191D)
val HPreDarkSurfaceContainer = Color(0xFF1E2025)
val HPreDarkSurfaceContainerHigh = Color(0xFF25282E)
val HPreDarkSurfaceContainerHighest = Color(0xFF2D3038)
val HPreDarkSurfaceVariant = Color(0xFF292C33)
val HPreDarkOnSurface = Color(0xFFF4F4F5)
val HPreDarkOnSurfaceVariant = Color(0xFFB4B6BF)
val HPreDarkPrimary = Color(0xFFFFB4AB)
val HPreDarkOnPrimary = Color(0xFF690005)
val HPreDarkPrimaryContainer = Color(0xFF8C1D18)
val HPreDarkOnPrimaryContainer = Color(0xFFFFDAD6)
val HPreDarkSecondary = Color(0xFFC7C9D1)
val HPreDarkOnSecondary = Color(0xFF101114)
val HPreDarkSecondaryContainer = Color(0xFF2D3038)
val HPreDarkOnSecondaryContainer = Color(0xFFF4F4F5)
val HPreDarkOutline = Color(0xFF8A8D99)
val HPreDarkOutlineVariant = Color(0xFF3A3D46)
val HPreDarkError = Color(0xFFF2B8B5)
val HPreDarkOnError = Color(0xFF601410)
val HPreDarkErrorContainer = Color(0xFF8C1D18)
val HPreDarkOnErrorContainer = Color(0xFFF9DEDC)
val HPreDarkInverseSurface = Color(0xFFE4E4E8)
val HPreDarkInverseOnSurface = Color(0xFF2A2B30)
val HPreDarkSurfaceDim = Color(0xFF0B0C0F)
val HPreDarkSurfaceBright = Color(0xFF383A42)

// Light theme — spec section 2.3
val HPreLightBackground = Color(0xFFFAFAFC)
val HPreLightSurface = Color(0xFFFFFFFF)
val HPreLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val HPreLightSurfaceContainerLow = Color(0xFFF5F5F8)
val HPreLightSurfaceContainer = Color(0xFFEEEEF3)
val HPreLightSurfaceContainerHigh = Color(0xFFE8E8EE)
val HPreLightSurfaceContainerHighest = Color(0xFFE1E1E8)
val HPreLightSurfaceVariant = Color(0xFFE9E9F0)
val HPreLightOnSurface = Color(0xFF18191D)
val HPreLightOnSurfaceVariant = Color(0xFF5F626D)
val HPreLightPrimary = Color(0xFFB32624)
val HPreLightOnPrimary = Color(0xFFFFFFFF)
val HPreLightPrimaryContainer = Color(0xFFFFDAD6)
val HPreLightOnPrimaryContainer = Color(0xFF410002)
val HPreLightSecondary = Color(0xFF5F626D)
val HPreLightOnSecondary = Color(0xFFFFFFFF)
val HPreLightSecondaryContainer = Color(0xFFE1E1E8)
val HPreLightOnSecondaryContainer = Color(0xFF18191D)
val HPreLightOutline = Color(0xFF7A7B85)
val HPreLightOutlineVariant = Color(0xFFD3D3DB)
val HPreLightError = Color(0xFFB3261D)
val HPreLightOnError = Color(0xFFFFFFFF)
val HPreLightErrorContainer = Color(0xFFF9DEDC)
val HPreLightOnErrorContainer = Color(0xFF410002)
val HPreLightInverseSurface = Color(0xFF2E2F34)
val HPreLightInverseOnSurface = Color(0xFFF5F5F8)
val HPreLightSurfaceDim = Color(0xFFDADBE2)
val HPreLightSurfaceBright = Color(0xFFFFFFFF)
