package com.hpre.app.model

data class VideoStream(
    val url: String,
    val format: String,
    val resolution: String,
    val width: Int?,
    val height: Int?,
    val bitrate: Long?,
    val isVideoOnly: Boolean = false,
    val mimeType: String? = null,
    val codec: String? = null
)

data class AudioStream(
    val url: String,
    val format: String,
    val bitrate: Long?,
    val averageBitrate: Long? = null,
    val language: String? = null,
    val mimeType: String? = null,
    val codec: String? = null
)

data class SubtitleStream(
    val url: String,
    val language: String,
    val format: String,
    val isAutoGenerated: Boolean = false,
    val mimeType: String? = null
)

data class StreamInfo(
    val key: ContentKey,
    val title: String,
    val videoStreams: List<VideoStream> = emptyList(),
    val audioStreams: List<AudioStream> = emptyList(),
    val subtitles: List<SubtitleStream> = emptyList(),
    val hlsManifestUrl: String? = null,
    val dashManifestUrl: String? = null,
    val isLive: Boolean = false
)

