package com.hpre.app.model

data class VideoStream(
    val url: String,
    val format: String,
    val resolution: String,
    val width: Int?,
    val height: Int?,
    val bitrate: Long?,
    val isVideoOnly: Boolean = false,
    val mimeType: String? = null,
    val codec: String? = null,
    val streamId: String? = null,
    val deliveryMethod: VideoDeliveryMethod? = null
)

data class AudioStream(
    val url: String,
    val format: String,
    val bitrate: Long?,
    val averageBitrate: Long? = null,
    val language: String? = null,
    val mimeType: String? = null,
    val codec: String? = null,
    val streamId: String? = null,
    val audioTrackId: String? = null
)

data class SubtitleStream(
    val url: String,
    val language: String,
    val format: String,
    val isAutoGenerated: Boolean = false,
    val mimeType: String? = null
)

data class StreamInfo(
    val key: ContentKey,
    val title: String,
    val videoStreams: List<VideoStream> = emptyList(),
    val audioStreams: List<AudioStream> = emptyList(),
    val subtitles: List<SubtitleStream> = emptyList(),
    val hlsManifestUrl: String? = null,
    val dashManifestUrl: String? = null,
    val isLive: Boolean = false
)

fun StreamInfo.playableMediaUrls(): List<String> = buildList {
    videoStreams.mapTo(this) { it.url }
    audioStreams.mapTo(this) { it.url }
    hlsManifestUrl?.let(::add)
    dashManifestUrl?.let(::add)
}.filter(String::isNotBlank)

fun StreamInfo.earliestMediaUrlExpiryMs(): Long? = playableMediaUrls()
    .asSequence()
    .flatMap(::expiryValues)
    .mapNotNull(::parseExpiryMs)
    .minOrNull()

fun StreamInfo.hasUsableMediaUrls(
    currentTimeMs: Long = System.currentTimeMillis(),
    safetyMarginMs: Long = 5_000L
): Boolean {
    val urls = playableMediaUrls()
    if (urls.isEmpty()) return false
    val expiry = earliestMediaUrlExpiryMs()
    return expiry == null || currentTimeMs < expiry - safetyMarginMs
}

private fun expiryValues(url: String): Sequence<String> = sequence {
    val query = runCatching { java.net.URI(url).rawQuery }.getOrNull() ?: return@sequence
    for (pair in query.split('&')) {
        val parts = pair.split('=', limit = 2)
        if (parts.size != 2) continue
        val name = decode(parts[0]) ?: continue
        if (name.equals("expire", true) || name.equals("expires", true) || name.equals("expiry", true)) {
            decode(parts[1])?.let { yield(it) }
        }
    }
}

private fun decode(value: String): String? = runCatching {
    java.net.URLDecoder.decode(value, java.nio.charset.StandardCharsets.UTF_8.name())
}.getOrNull()

private fun parseExpiryMs(value: String): Long? {
    val parsed = value.toLongOrNull()?.takeIf { it > 0L } ?: return null
    return if (parsed < EPOCH_MILLISECONDS_THRESHOLD) {
        runCatching { Math.multiplyExact(parsed, 1_000L) }.getOrNull()
    } else {
        parsed
    }
}

private const val EPOCH_MILLISECONDS_THRESHOLD = 10_000_000_000L


